
/** required package class namespace */
package game;


/**
 * UserInterface.java - the user interface for the game
 *
 * @author Mr. Wachs 
 * @since 15-May-2019 
 */
public class UserInterface extends javax.swing.JFrame 
{

    
    /** Creates new form UserInterface */
    public UserInterface() {
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heroLabel = new javax.swing.JLabel();
        enemy1Label = new javax.swing.JLabel();
        enemy2Label = new javax.swing.JLabel();
        objectiveLabel = new javax.swing.JLabel();
        wall01Label = new javax.swing.JLabel();
        wall02Label = new javax.swing.JLabel();
        wall03Label = new javax.swing.JLabel();
        wall04Label = new javax.swing.JLabel();
        wall05Label = new javax.swing.JLabel();
        wall06Label = new javax.swing.JLabel();
        wall07Label = new javax.swing.JLabel();
        wall08Label = new javax.swing.JLabel();
        wall09Label = new javax.swing.JLabel();
        wall10Label = new javax.swing.JLabel();
        prize1Label = new javax.swing.JLabel();
        prize2Label = new javax.swing.JLabel();
        prize3Label = new javax.swing.JLabel();
        prize4Label = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        heroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heroLabel.setText("HERO");
        heroLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        enemy1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enemy1Label.setText("ENEMY");
        enemy1Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        enemy2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enemy2Label.setText("ENEMY");
        enemy2Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        objectiveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        objectiveLabel.setText("OBJECTIVE");
        objectiveLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall01Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall01Label.setText("WALL");
        wall01Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall02Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall02Label.setText("WALL");
        wall02Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall03Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall03Label.setText("WALL");
        wall03Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall04Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall04Label.setText("WALL");
        wall04Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall05Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall05Label.setText("WALL");
        wall05Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall06Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall06Label.setText("WALL");
        wall06Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall07Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall07Label.setText("WALL");
        wall07Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall08Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall08Label.setText("WALL");
        wall08Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall09Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall09Label.setText("WALL");
        wall09Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wall10Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wall10Label.setText("WALL");
        wall10Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prize1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prize1Label.setText("PRIZE");
        prize1Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prize2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prize2Label.setText("PRIZE");
        prize2Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prize3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prize3Label.setText("PRIZE");
        prize3Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prize4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prize4Label.setText("PRIZE");
        prize4Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        backgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundLabel.setText("BACKGROUND");
        backgroundLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(wall01Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(enemy1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(prize2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wall09Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(390, 390, 390)
                .addComponent(wall04Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(wall02Label, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(wall07Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(wall06Label, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(wall08Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(enemy2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(prize4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(wall05Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(860, 860, 860)
                .addComponent(heroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(wall10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(prize3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(objectiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(prize1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(wall03Label, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(wall01Label, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(enemy1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(prize2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(wall09Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(wall04Label, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(wall02Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(wall07Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(wall06Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(wall08Label, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(enemy2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(prize4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(wall05Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(heroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(wall10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(prize3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(objectiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(prize1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(wall03Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel enemy1Label;
    private javax.swing.JLabel enemy2Label;
    private javax.swing.JLabel heroLabel;
    private javax.swing.JLabel objectiveLabel;
    private javax.swing.JLabel prize1Label;
    private javax.swing.JLabel prize2Label;
    private javax.swing.JLabel prize3Label;
    private javax.swing.JLabel prize4Label;
    private javax.swing.JLabel wall01Label;
    private javax.swing.JLabel wall02Label;
    private javax.swing.JLabel wall03Label;
    private javax.swing.JLabel wall04Label;
    private javax.swing.JLabel wall05Label;
    private javax.swing.JLabel wall06Label;
    private javax.swing.JLabel wall07Label;
    private javax.swing.JLabel wall08Label;
    private javax.swing.JLabel wall09Label;
    private javax.swing.JLabel wall10Label;
    // End of variables declaration//GEN-END:variables

}
