
/** required package class namespace */
package game;

/** required imports */
import javax.swing.JLabel;


/**
 * UserInterface.java - the user interface for the game
 *
 * @author Mr. Wachs 
 * @since 3-Jun-2019 
 */
public class UserInterface extends javax.swing.JFrame 
{
    
    GameEngine engine;

    /** Creates new form UserInterface */
    public UserInterface() {
        initComponents();        
        JLabel[] wallLabels = {
            lblWall1,lblWall2,lblWall3,
            lblWall4,lblWall5,lblWall6,
            lblWall7,lblWall8,lblWall9,
            lblWall10,lblWall11,lblWall12,
            lblWall13,lblWall14,lblWall15,
            lblWall16,lblWall17,lblWall18,
            lblWall19,lblWall20,lblWall21,
            lblWall22,lblWall23,lblWall24,
            lblWall25,lblWall26,lblWall27,
            lblWall28,lblWall29,lblWall30,
            lblWall31,lblWall32,lblWall33,
            lblWall34,lblWall35,lblWall36,
            lblWall37,lblWall38,lblWall39,
            lblWall40,lblWall41,lblWall42,
            lblWall43,lblWall44                        
        };
        JLabel[] dotLabels = {
            lblDot1,lblDot2,
            lblDot3,lblDot4
        };
        JLabel[] ghostLabels = {
            ghostLabel1,ghostLabel2,ghostLabel3,ghostLabel4
        };
        engine = new GameEngine(pacmanLabel,backgroundLabel,wallLabels,
                            dotLabels,ghostLabels,this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pacmanLabel = new javax.swing.JLabel();
        ghostLabel1 = new javax.swing.JLabel();
        ghostLabel2 = new javax.swing.JLabel();
        ghostLabel3 = new javax.swing.JLabel();
        ghostLabel4 = new javax.swing.JLabel();
        lblDot1 = new javax.swing.JLabel();
        lblDot2 = new javax.swing.JLabel();
        lblDot3 = new javax.swing.JLabel();
        lblDot4 = new javax.swing.JLabel();
        lblWall1 = new javax.swing.JLabel();
        lblWall2 = new javax.swing.JLabel();
        lblWall3 = new javax.swing.JLabel();
        lblWall4 = new javax.swing.JLabel();
        lblWall5 = new javax.swing.JLabel();
        lblWall6 = new javax.swing.JLabel();
        lblWall7 = new javax.swing.JLabel();
        lblWall8 = new javax.swing.JLabel();
        lblWall9 = new javax.swing.JLabel();
        lblWall10 = new javax.swing.JLabel();
        lblWall11 = new javax.swing.JLabel();
        lblWall12 = new javax.swing.JLabel();
        lblWall13 = new javax.swing.JLabel();
        lblWall14 = new javax.swing.JLabel();
        lblWall15 = new javax.swing.JLabel();
        lblWall16 = new javax.swing.JLabel();
        lblWall17 = new javax.swing.JLabel();
        lblWall18 = new javax.swing.JLabel();
        lblWall19 = new javax.swing.JLabel();
        lblWall20 = new javax.swing.JLabel();
        lblWall21 = new javax.swing.JLabel();
        lblWall22 = new javax.swing.JLabel();
        lblWall23 = new javax.swing.JLabel();
        lblWall24 = new javax.swing.JLabel();
        lblWall25 = new javax.swing.JLabel();
        lblWall26 = new javax.swing.JLabel();
        lblWall27 = new javax.swing.JLabel();
        lblWall28 = new javax.swing.JLabel();
        lblWall29 = new javax.swing.JLabel();
        lblWall30 = new javax.swing.JLabel();
        lblWall31 = new javax.swing.JLabel();
        lblWall32 = new javax.swing.JLabel();
        lblWall33 = new javax.swing.JLabel();
        lblWall34 = new javax.swing.JLabel();
        lblWall35 = new javax.swing.JLabel();
        lblWall36 = new javax.swing.JLabel();
        lblWall37 = new javax.swing.JLabel();
        lblWall38 = new javax.swing.JLabel();
        lblWall39 = new javax.swing.JLabel();
        lblWall40 = new javax.swing.JLabel();
        lblWall41 = new javax.swing.JLabel();
        lblWall42 = new javax.swing.JLabel();
        lblWall43 = new javax.swing.JLabel();
        lblWall44 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        pacmanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pacmanLabel.setText("PACMAN");
        pacmanLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(pacmanLabel);
        pacmanLabel.setBounds(420, 490, 30, 30);

        ghostLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghostLabel1.setText("GHOST");
        ghostLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(ghostLabel1);
        ghostLabel1.setBounds(150, 620, 30, 30);

        ghostLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghostLabel2.setText("GHOST");
        ghostLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(ghostLabel2);
        ghostLabel2.setBounds(500, 350, 30, 30);

        ghostLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghostLabel3.setText("GHOST");
        ghostLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(ghostLabel3);
        ghostLabel3.setBounds(540, 630, 30, 30);

        ghostLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghostLabel4.setText("GHOST");
        ghostLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(ghostLabel4);
        ghostLabel4.setBounds(150, 140, 30, 30);

        lblDot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot1.setText("DOT");
        lblDot1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot1);
        lblDot1.setBounds(40, 60, 15, 15);

        lblDot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot2.setText("DOT");
        lblDot2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot2);
        lblDot2.setBounds(330, 360, 15, 15);

        lblDot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot3.setText("DOT");
        lblDot3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot3);
        lblDot3.setBounds(620, 700, 15, 15);

        lblDot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot4.setText("DOT");
        lblDot4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot4);
        lblDot4.setBounds(50, 710, 15, 15);

        lblWall1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall1.setText("WALL");
        lblWall1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall1);
        lblWall1.setBounds(10, 30, 650, 20);

        lblWall2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall2.setText("WALL");
        lblWall2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall2);
        lblWall2.setBounds(10, 30, 20, 720);

        lblWall3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall3.setText("WALL");
        lblWall3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall3);
        lblWall3.setBounds(10, 740, 660, 20);

        lblWall4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall4.setText("WALL");
        lblWall4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall4);
        lblWall4.setBounds(650, 30, 20, 720);

        lblWall5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall5.setText("WALL");
        lblWall5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall5);
        lblWall5.setBounds(186, 180, 20, 160);

        lblWall6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall6.setText("WALL");
        lblWall6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall6);
        lblWall6.setBounds(390, 670, 210, 20);

        lblWall7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall7.setText("WALL");
        lblWall7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall7);
        lblWall7.setBounds(20, 600, 50, 20);

        lblWall8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall8.setText("WALL");
        lblWall8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall8);
        lblWall8.setBounds(10, 390, 130, 90);

        lblWall9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall9.setText("WALL");
        lblWall9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall9);
        lblWall9.setBounds(470, 600, 20, 90);

        lblWall10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall10.setText("WALL");
        lblWall10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall10);
        lblWall10.setBounds(260, 600, 160, 20);

        lblWall11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall11.setText("WALL");
        lblWall11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall11);
        lblWall11.setBounds(400, 250, 90, 20);

        lblWall12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall12.setText("WALL");
        lblWall12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall12);
        lblWall12.setBounds(470, 180, 20, 160);

        lblWall13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall13.setText("WALL");
        lblWall13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall13);
        lblWall13.setBounds(190, 600, 20, 90);

        lblWall14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall14.setText("WALL");
        lblWall14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall14);
        lblWall14.setBounds(70, 670, 210, 20);

        lblWall15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall15.setText("WALL");
        lblWall15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall15);
        lblWall15.setBounds(186, 250, 90, 20);

        lblWall16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall16.setText("WALL");
        lblWall16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall16);
        lblWall16.setBounds(260, 180, 160, 20);

        lblWall17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall17.setText("WALL");
        lblWall17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall17);
        lblWall17.setBounds(530, 90, 70, 40);

        lblWall18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall18.setText("WALL");
        lblWall18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall18);
        lblWall18.setBounds(10, 250, 130, 90);

        lblWall19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall19.setText("WALL");
        lblWall19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall19);
        lblWall19.setBounds(540, 250, 130, 90);

        lblWall20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall20.setText("WALL");
        lblWall20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall20);
        lblWall20.setBounds(540, 390, 130, 90);

        lblWall21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall21.setText("WALL");
        lblWall21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall21);
        lblWall21.setBounds(70, 90, 70, 40);

        lblWall22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall22.setText("WALL");
        lblWall22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall22);
        lblWall22.setBounds(190, 90, 90, 40);

        lblWall23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall23.setText("WALL");
        lblWall23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall23);
        lblWall23.setBounds(400, 90, 90, 40);

        lblWall24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall24.setText("WALL");
        lblWall24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall24);
        lblWall24.setBounds(320, 40, 30, 90);

        lblWall25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall25.setText("WALL");
        lblWall25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall25);
        lblWall25.setBounds(330, 610, 20, 80);

        lblWall26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall26.setText("WALL");
        lblWall26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall26);
        lblWall26.setBounds(330, 190, 20, 80);

        lblWall27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall27.setText("WALL");
        lblWall27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall27);
        lblWall27.setBounds(70, 180, 70, 20);

        lblWall28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall28.setText("WALL");
        lblWall28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall28);
        lblWall28.setBounds(530, 180, 70, 20);

        lblWall29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall29.setText("WALL");
        lblWall29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall29);
        lblWall29.setBounds(600, 600, 50, 20);

        lblWall30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall30.setText("WALL");
        lblWall30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall30);
        lblWall30.setBounds(470, 390, 20, 100);

        lblWall31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall31.setText("WALL");
        lblWall31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall31);
        lblWall31.setBounds(260, 460, 160, 20);

        lblWall32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall32.setText("WALL");
        lblWall32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall32);
        lblWall32.setBounds(330, 470, 20, 80);

        lblWall33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall33.setText("WALL");
        lblWall33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall33);
        lblWall33.setBounds(120, 530, 20, 90);

        lblWall34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall34.setText("WALL");
        lblWall34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall34);
        lblWall34.setBounds(190, 390, 20, 100);

        lblWall35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall35.setText("WALL");
        lblWall35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall35);
        lblWall35.setBounds(70, 530, 70, 20);

        lblWall36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall36.setText("WALL");
        lblWall36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall36);
        lblWall36.setBounds(260, 400, 160, 20);

        lblWall37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall37.setText("WALL");
        lblWall37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall37);
        lblWall37.setBounds(530, 530, 20, 90);

        lblWall38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall38.setText("WALL");
        lblWall38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall38);
        lblWall38.setBounds(540, 530, 70, 20);

        lblWall39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall39.setText("WALL");
        lblWall39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall39);
        lblWall39.setBounds(400, 530, 90, 20);

        lblWall40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall40.setText("WALL");
        lblWall40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall40);
        lblWall40.setBounds(190, 530, 90, 20);

        lblWall41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall41.setText("WALL");
        lblWall41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall41);
        lblWall41.setBounds(400, 320, 20, 100);

        lblWall42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall42.setText("WALL");
        lblWall42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall42);
        lblWall42.setBounds(250, 320, 20, 100);

        lblWall43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall43.setText("WALL");
        lblWall43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall43);
        lblWall43.setBounds(250, 320, 50, 20);

        lblWall44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall44.setText("WALL");
        lblWall44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall44);
        lblWall44.setBounds(370, 320, 50, 20);

        backgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundLabel.setText("BACKGROUND");
        backgroundLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 10, 690, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        engine.keypress(evt);
    }//GEN-LAST:event_formKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel ghostLabel1;
    private javax.swing.JLabel ghostLabel2;
    private javax.swing.JLabel ghostLabel3;
    private javax.swing.JLabel ghostLabel4;
    private javax.swing.JLabel lblDot1;
    private javax.swing.JLabel lblDot2;
    private javax.swing.JLabel lblDot3;
    private javax.swing.JLabel lblDot4;
    private javax.swing.JLabel lblWall1;
    private javax.swing.JLabel lblWall10;
    private javax.swing.JLabel lblWall11;
    private javax.swing.JLabel lblWall12;
    private javax.swing.JLabel lblWall13;
    private javax.swing.JLabel lblWall14;
    private javax.swing.JLabel lblWall15;
    private javax.swing.JLabel lblWall16;
    private javax.swing.JLabel lblWall17;
    private javax.swing.JLabel lblWall18;
    private javax.swing.JLabel lblWall19;
    private javax.swing.JLabel lblWall2;
    private javax.swing.JLabel lblWall20;
    private javax.swing.JLabel lblWall21;
    private javax.swing.JLabel lblWall22;
    private javax.swing.JLabel lblWall23;
    private javax.swing.JLabel lblWall24;
    private javax.swing.JLabel lblWall25;
    private javax.swing.JLabel lblWall26;
    private javax.swing.JLabel lblWall27;
    private javax.swing.JLabel lblWall28;
    private javax.swing.JLabel lblWall29;
    private javax.swing.JLabel lblWall3;
    private javax.swing.JLabel lblWall30;
    private javax.swing.JLabel lblWall31;
    private javax.swing.JLabel lblWall32;
    private javax.swing.JLabel lblWall33;
    private javax.swing.JLabel lblWall34;
    private javax.swing.JLabel lblWall35;
    private javax.swing.JLabel lblWall36;
    private javax.swing.JLabel lblWall37;
    private javax.swing.JLabel lblWall38;
    private javax.swing.JLabel lblWall39;
    private javax.swing.JLabel lblWall4;
    private javax.swing.JLabel lblWall40;
    private javax.swing.JLabel lblWall41;
    private javax.swing.JLabel lblWall42;
    private javax.swing.JLabel lblWall43;
    private javax.swing.JLabel lblWall44;
    private javax.swing.JLabel lblWall5;
    private javax.swing.JLabel lblWall6;
    private javax.swing.JLabel lblWall7;
    private javax.swing.JLabel lblWall8;
    private javax.swing.JLabel lblWall9;
    private javax.swing.JLabel pacmanLabel;
    // End of variables declaration//GEN-END:variables

}
