
/** required package class namespace */
package game;

import javax.swing.JLabel;


/**
 * UserInterface.java - 
 *
 * @author Mr. Wachs 
 * @since 3-Jun-2019 
 */
public class UserInterface extends javax.swing.JFrame 
{
    
    GameEngine engine;

    /** Creates new form UserInterface */
    public UserInterface() {
        initComponents();        
        JLabel[] wallLabels = {
            lblWall1,lblWall2,lblWall3,
            lblWall4,lblWall5,lblWall6  
        };
        JLabel[] dotLabels = {
            lblDot1,lblDot2,
            lblDot3,lblDot4
        };
        JLabel[] ghostLabels = {
            ghost1Label1,ghost2Label
        };
        engine = new GameEngine(pacmanLabel,backgroundLabel,wallLabels,
                            dotLabels,ghostLabels,this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pacmanLabel = new javax.swing.JLabel();
        ghost1Label1 = new javax.swing.JLabel();
        ghost2Label = new javax.swing.JLabel();
        lblDot1 = new javax.swing.JLabel();
        lblDot2 = new javax.swing.JLabel();
        lblDot3 = new javax.swing.JLabel();
        lblDot4 = new javax.swing.JLabel();
        lblWall1 = new javax.swing.JLabel();
        lblWall2 = new javax.swing.JLabel();
        lblWall3 = new javax.swing.JLabel();
        lblWall4 = new javax.swing.JLabel();
        lblWall5 = new javax.swing.JLabel();
        lblWall6 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        pacmanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pacmanLabel.setText("PACMAN");
        pacmanLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(pacmanLabel);
        pacmanLabel.setBounds(560, 100, 50, 50);

        ghost1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghost1Label1.setText("GHOST");
        ghost1Label1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(ghost1Label1);
        ghost1Label1.setBounds(140, 110, 50, 50);

        ghost2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghost2Label.setText("GHOST");
        ghost2Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(ghost2Label);
        ghost2Label.setBounds(310, 670, 50, 50);

        lblDot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot1.setText("DOT");
        lblDot1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot1);
        lblDot1.setBounds(40, 70, 25, 25);

        lblDot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot2.setText("DOT");
        lblDot2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot2);
        lblDot2.setBounds(330, 340, 25, 25);

        lblDot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot3.setText("DOT");
        lblDot3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot3);
        lblDot3.setBounds(620, 700, 25, 25);

        lblDot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDot4.setText("DOT");
        lblDot4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDot4);
        lblDot4.setBounds(100, 610, 25, 25);

        lblWall1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall1.setText("WALL");
        lblWall1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall1);
        lblWall1.setBounds(10, 30, 650, 20);

        lblWall2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall2.setText("WALL");
        lblWall2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall2);
        lblWall2.setBounds(10, 30, 20, 720);

        lblWall3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall3.setText("WALL");
        lblWall3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall3);
        lblWall3.setBounds(10, 750, 660, 10);

        lblWall4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall4.setText("WALL");
        lblWall4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall4);
        lblWall4.setBounds(650, 30, 20, 720);

        lblWall5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall5.setText("WALL");
        lblWall5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall5);
        lblWall5.setBounds(190, 180, 31, 160);

        lblWall6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWall6.setText("WALL");
        lblWall6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblWall6);
        lblWall6.setBounds(400, 670, 210, 20);

        backgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundLabel.setText("BACKGROUND");
        backgroundLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 10, 690, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        engine.keypress(evt);
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel ghost1Label1;
    private javax.swing.JLabel ghost2Label;
    private javax.swing.JLabel lblDot1;
    private javax.swing.JLabel lblDot2;
    private javax.swing.JLabel lblDot3;
    private javax.swing.JLabel lblDot4;
    private javax.swing.JLabel lblWall1;
    private javax.swing.JLabel lblWall2;
    private javax.swing.JLabel lblWall3;
    private javax.swing.JLabel lblWall4;
    private javax.swing.JLabel lblWall5;
    private javax.swing.JLabel lblWall6;
    private javax.swing.JLabel pacmanLabel;
    // End of variables declaration//GEN-END:variables

}
