
/** Required package class namespace */
package testing.prerequisite.cs20s;

import java.util.Random;


/**
 * Unit5Looping1.java - this is a Visual Studio (C#) Windows Form
 * adaptation into NetBeans (Java) JFrame (some code may not translate)
 *
 * @author Mr. Wachs
 * @since Feb 22, 2024, 3:16:32 p.m.
 */
public class Unit5Looping1 extends javax.swing.JFrame 
{

    
    
    /** 
     * Default constructor, creates new form Unit5Looping1 
     */
    public Unit5Looping1() {
        initComponents();        
        this.getContentPane().setLayout(null);        
        this.setTitle("Unit 5 Looping 1");
        this.setSize(600, 400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        // Code to add things to the combo box...

        cboValues.add("10");
        cboValues.add("100");
        cboValues.add("1000");
        cboValues.add("10000");

        // Also change the text inside
        // (like a textbox)

        cboValues.add("0");
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="NetBeans Generated Code">

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMax = new javax.swing.JLabel();
        cboValues = new java.awt.Choice();
        lstNumbers = new java.awt.List();
        btnFind = new javax.swing.JButton();
        lblDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblMax.setText("Maximum:");
        getContentPane().add(lblMax);
        lblMax.setBounds(10, 20, 80, 20);
        getContentPane().add(cboValues);
        cboValues.setBounds(100, 20, 110, 20);
        getContentPane().add(lstNumbers);
        lstNumbers.setBounds(10, 50, 200, 300);

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind);
        btnFind.setBounds(220, 20, 390, 23);

        lblDisplay.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblDisplay);
        lblDisplay.setBounds(220, 50, 390, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // </editor-fold>
    
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // Clear out the list box
        // (same code works on combobox)

        lstNumbers.removeAll();

        // Make a random number generator

        Random random = new Random();

        // Make some variables
        // (the comma is not recommended)

        int number = 0, guess = 0;

        // Another variable which reads from the combobox 
        // (like we did with textboxes)

        String value = cboValues.getSelectedItem().trim();

        // ".Trim()" removes any extra leading or trailing spaces
        // (at the beginning or the end)

        int max = Integer.parseInt(value);

        // Converting the text to a number
        // (from the combobox)

        int answer = random.nextInt(max - 1) + 1; 

        // Generating a random answer 
        // (for the computer to guess)

        // The Loop code...

        while (number != answer)
        {

            // Count a guess 
            // (using the optional shorthand)

            guess++;

            // This shorthand means guess = guess + 1

            number = random.nextInt(max - 1) + 1;

            // Making a guess for the number

            // Display that guess 
            // (in the listbox)

            lstNumbers.add("Guess " + guess + " = " + number);

        }

        // Show the user the final results...

        lblDisplay.setText("It took me " + guess +
            " guesses to find the number " + answer +
            " between 1 and " + max);
        
    }//GEN-LAST:event_btnFindActionPerformed

    
    
    // <editor-fold defaultstate="collapsed" desc="NetBeans Generated Code">
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private java.awt.Choice cboValues;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblMax;
    private java.awt.List lstNumbers;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>
    
}
