
/** Required package class namespace */
package finalproject;

/** Required code library (API) imports */
import javax.swing.JOptionPane;


/**
 * AllUsersUI.java - this second UI is for the user to modify the list of all
 * users.
 * 
 * @author Mr. Wachs
 * @since January 2026
 */
public class AllUsersUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(AllUsersUI.class.getName());

    
    /**
     * Class constructor, it creates new form AllUsersUI using a call to the 
     * designer written method "initComponents"
     */
    public AllUsersUI() {
        initComponents();
        
        // =====================================================================
        updateList();                         // Call method to fill the listbox
        
        // Set other UI properties...      
        this.setResizable(false);                       // Make form not sizable
        this.setSize(475, 445);                                 // Set form size
        this.setLocationRelativeTo(null);               // Center form on screen
        this.setVisible(true);                              // Show form to user
        // =====================================================================
    }

    /**
     * This method updates and fills the listbox control on the UI by looping
     * through the LinkedList of users and adding them into the listbox
     */
    private void updateList() {
        // Clear out the listbox first
        list1.removeAll();
        // Load all the users into the listbox
        for (int i = 0; i < Globals.users.size(); i++) {        // Traverse list
            User user = Globals.users.get(i);       // Get user object from list
            String information = user.toString();   // Get information from user
            list1.add(information);                // Add information to listbox
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("All Users:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 240, 16);
        getContentPane().add(list1);
        list1.setBounds(10, 30, 240, 360);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 130, 180, 40);

        jButton2.setText("DELETE SELECTED USER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 30, 180, 40);

        jButton3.setText("SORT LIST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 80, 180, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // =====================================================================
        new LoginUI();                 // Instantiate and show the previous form
        this.dispose();                  // Dispose and hide current (this) form
        // =====================================================================
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // =====================================================================
        JOptionPane.showMessageDialog(this, "Please upgrade for this feature!");
        // =====================================================================
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // =====================================================================        
        int index = list1.getSelectedIndex(); // Get user selection from listbox
        Globals.users.remove(index);   // Remove that index from the linked list
        updateList();                         // Call method to fill the listbox
        // =====================================================================
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
