
/** Required package class namespace */
package finalproject;

/** Required code library (API) imports */
import javax.swing.JOptionPane;


/**
 * LoginUI.java - this user interface (UI) built with the NetBeans visual
 * designer.
 * 
 * @author Mr. Wachs
 * @since January 2026
 */
public class LoginUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(LoginUI.class.getName());

    
    /**
     * Class constructor, it creates new form LoginUI using a call to the 
     * designer written method "initComponents"
     */
    public LoginUI() {
        initComponents();
        
        // =====================================================================
        // Set other UI properties...        
        this.setResizable(false);                       // Make form not sizable
        this.setSize(330, 300);                                 // Set form size
        this.setLocationRelativeTo(null);               // Center form on screen
        this.setVisible(true);                              // Show form to user
        // =====================================================================
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        editUsersButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("NAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(21, 24, 110, 16);
        getContentPane().add(nameTextField);
        nameTextField.setBounds(132, 21, 160, 22);

        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 64, 110, 16);
        getContentPane().add(passwordField);
        passwordField.setBounds(132, 61, 160, 22);

        loginButton.setText("LOGIN EXISTING USER");
        loginButton.setToolTipText("");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(21, 101, 270, 39);

        editUsersButton.setText("EDIT ALL USERS");
        editUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editUsersButton);
        editUsersButton.setBounds(20, 200, 270, 46);

        addUserButton.setText("ADD NEW USER");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addUserButton);
        addUserButton.setBounds(21, 146, 270, 46);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsersButtonActionPerformed
        // =====================================================================
        new AllUsersUI();                  // Instantiate and show the next form
        this.dispose();                  // Dispose and hide current (this) form
        // =====================================================================
    }//GEN-LAST:event_editUsersButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // =====================================================================
        // Get the user information from the UI controls (text and password
        // fields) and assign to variables and then into a User object        
        String name = nameTextField.getText();                      // User name
        char[] characters = passwordField.getPassword();        // User password
        String password = new String(characters);  // Convert password to string
        
        // Create a User object from variables using class constructor
        User user = new User(name, password);
        
        // Add the new User object to our shared LinkedList object
        Globals.users.add(user);
        
        // Tell the user they were successful and clear the fields
        JOptionPane.showMessageDialog(this, "Success, user added!");
        nameTextField.setText("");
        passwordField.setText("");
        // =====================================================================
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // =====================================================================
        // Get the user information from the UI controls (text and password
        // fields) and assign to variables and then into a User object        
        String name = nameTextField.getText();                      // User name
        char[] characters = passwordField.getPassword();        // User password
        String password = new String(characters);  // Convert password to string
        
        // Create a User object from variables using class constructor
        User currentUser = new User(name, password);
        
        // Search through the LinkedList  of users for this current user
        for (int i = 0; i < Globals.users.size(); i++) {        // Traverse list
            User existingUser = Globals.users.get(i);      // Get user from list
            if (currentUser.equals(existingUser)) {      // Compare user objects
                // Using the overloaded "equals" method of the User class, this
                // indicates the current user matches with a user object that
                // does exist in the database
                JOptionPane.showMessageDialog(this, "User exists!"); 
                System.exit(0);             
                // Here we exit the program, but in a more realistic final 
                // project, you would move to the next form of the project
            }
        }
        
        // If the logic makes it through the loop of all users and does not
        // match with any users, then the current user is not in the list
        JOptionPane.showMessageDialog(this, "User does not exist!");
        // =====================================================================
    }//GEN-LAST:event_loginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton editUsersButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
