/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import javax.swing.JOptionPane;

/**
 *
 * @author lawrence.wachs
 */
public class LoginUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginUI.class.getName());

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        
        this.setResizable(false);
        this.setSize(330, 300);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        editUsersButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("NAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(21, 24, 110, 16);
        getContentPane().add(nameTextField);
        nameTextField.setBounds(132, 21, 160, 22);

        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 64, 110, 16);
        getContentPane().add(passwordField);
        passwordField.setBounds(132, 61, 160, 22);

        loginButton.setText("LOGIN EXISTING USER");
        loginButton.setToolTipText("");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(21, 101, 270, 39);

        editUsersButton.setText("EDIT ALL USERS");
        editUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editUsersButton);
        editUsersButton.setBounds(20, 200, 270, 46);

        addUserButton.setText("ADD NEW USER");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addUserButton);
        addUserButton.setBounds(21, 146, 270, 46);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsersButtonActionPerformed
        
        new AllUsersUI();
        this.dispose();
        
    }//GEN-LAST:event_editUsersButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed

        // Get the user information from the UI controls (text and password
        // fields)
        
        String name = nameTextField.getText();
        char[] characters = passwordField.getPassword();
        String password = new String(characters);
        
        // Create a user object
        User user = new User(name,password);
        
        // Add the user object to our linked list
        Globals.users.add(user);
        
        // Tell the user they were successful and clear the fields
        JOptionPane.showMessageDialog(this, "Success!");
        nameTextField.setText("");
        passwordField.setText("");
        
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        // Get the user information from the UI controls (text and password
        // fields)
        String name = nameTextField.getText();
        char[] characters = passwordField.getPassword();
        String password = new String(characters);
        
        // Create a user object
        User currentUser = new User(name,password);
        
        // Search through the linked list of users for this user
        for (int i = 0; i < Globals.users.size(); i++) {
            User existingUser = Globals.users.get(i);
            if (currentUser.equals(existingUser)) {
                // Are in the database
                JOptionPane.showMessageDialog(this, "User exists!");
                System.exit(0);
            }
        }
        
        JOptionPane.showMessageDialog(this, "User does not exist!");
        
    }//GEN-LAST:event_loginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton editUsersButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
