/** Required package class namespace */
package project.ui;

/** Required API imports */
import project.database.Checker;
import project.database.Database;
import project.tools.Message;
import project.tools.UITools;


/**
 * LogIn.java - a user interface (UI) for the application user to login to "any"
 * potential program (the one demonstrated in this example or anything like a 
 * game in your potential final projects). This class uses the NetBeans visual 
 * editor to design the UI, add controls (objects) from the pallette, and 
 * change properties using the properties window of the NetBeans designer. 
 * However, much of the logic for this program shifts to other classes and 
 * other UI classes such as:
 * 
 *  - Application.java: designer UI form for another form for the "project"
 *  - Checker.java:     class with static methods to error check
 *  - User.java:        class representing a user (with username and password)
 *  - Database.java:    class managing a LinkedList database of "User" objects
 *  - Person.java:      abstract class representing a Person with properties
 *  - Message.java:     abstract class with static methods for messages
 *  - UITools.java:     abstract class with static methods for forms
 * 
 * Also the project uses packages ("folders") to organize code modules and any
 * needed media (a picture) for the potential "project"
 *
 * @author Mr. Wachs
 * @since May 2026
 */
public class LogIn extends javax.swing.JFrame {
    
    // =========================================================================
    // The line below is added by the NetBeans editor, but can be left in place
    // or deleted... (I have commented it out)
    // =========================================================================
    
    // private static final java.util.logging.Logger logger = 
    //         java.util.logging.Logger.getLogger(LogIn.class.getName());

    /** 
     * Constructor method, creates new frame/form GUI 
     */
    public LogIn() {
        initComponents();                     // NetBeans designer method called
        UITools.setForm(this);                      // Set UI look and show user
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setText("Program Log in...");

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        okButton.setText("OK");
        okButton.setToolTipText("");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        newButton.setText("New User");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameTextField)
                                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addGap(18, 18, 18)
                .addComponent(newButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Call private encapsulated utility method to validate the text
        // fields and ensure they have content
        if (validateFields()) {                              // Fields are valid
            String username = usernameTextField.getText();      // Get user name
            String password = passwordTextField.getText();       // and password
            if (Database.checkForUser(username, password)) {   // Check database
                new Application();                                    // Move on
                this.dispose();                                 // Hide login UI
            } 
            else {                                         // Fields are invalid
                Message.notInDatabase(this);
                usernameTextField.setText("");              // Clear both fields
                passwordTextField.setText("");
                usernameTextField.requestFocus(); // Set focus to username field
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // Validate text fields again
        if (validateFields()) {
            String username = usernameTextField.getText();      // Get user name
            String password = passwordTextField.getText();       // and password
            Database.addNewUser(username, password);     // Add user to database
        }
    }//GEN-LAST:event_newButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Validates the text fields on the UI by ensuring they have actual content 
     * and using the Checker class for further validation
     * 
     * @return fields are valid (true) or not (false)
     */
    private boolean validateFields() {
        if (!Checker.checkUsername(usernameTextField)) {       // Check username
            Message.fillInName(this, usernameTextField);
            return false;                                    // Invalid username
        }
        if (!Checker.checkPassword(passwordTextField)) {       // Check password
            Message.fillInPassword(this, passwordTextField);
            return false;                                    // Invalid password
        }
        return true;                              // Valid username and password
    }
}
