
/** Required package class namespace */
package computerscience30s;


/**
 * Graphics3.java - description
 *
 * @author Mr. Wachs
 * @since Dec 19, 2024, 9:09:01 a.m.
 */
public class Graphics3 extends javax.swing.JFrame 
{

    /** 
     * Constructor method, creates new frame/form Graphics3 
     */
    public Graphics3() {
        initComponents();
        
        this.setSize(800, 800);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblHero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        enemyLabel.setBackground(new java.awt.Color(255, 255, 0));
        enemyLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        enemyLabel.setForeground(new java.awt.Color(51, 51, 255));
        enemyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enemyLabel.setText("ENEMY");
        enemyLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        enemyLabel.setOpaque(true);
        getContentPane().add(enemyLabel);
        enemyLabel.setBounds(80, 60, 202, 154);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 5, true));
        jPanel1.setLayout(null);

        lblHero.setBackground(new java.awt.Color(255, 255, 0));
        lblHero.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHero.setForeground(new java.awt.Color(51, 51, 255));
        lblHero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHero.setText("HERO");
        lblHero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHero.setOpaque(true);
        jPanel1.add(lblHero);
        lblHero.setBounds(40, 30, 202, 154);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 230, 530, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphics3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphics3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphics3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphics3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphics3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enemyLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHero;
    // End of variables declaration//GEN-END:variables

}
