/** Required package class namespace */
package testing.extras.collections;

/** Required API imports */
import collections.LinkedList;
import java.awt.event.KeyEvent;


/**
 * CollectionsUserInterface.java - a bonus example of the collection unit code 
 * used in a more practical way. This is an example of a simple user interface
 * created using the NetBeans designer and incorporating the LinkedList ADT
 * we created in unit 4
 *
 * @author Mr. Wachs
 * @since December 2024
 */
public class CollectionsUserInterface extends javax.swing.JFrame 
{

    /** The LinkedList ADT created in class */
    private LinkedList<String> list = new LinkedList<>();
    
    
    /**
     * Default constructor method 
     */
    public CollectionsUserInterface() {
        initComponents();                        // Call NetBeans written method
        enterTextField.requestFocus();                   // Put focus on textbox
        this.setLocationRelativeTo(null);               // Center form on screen
        this.setVisible(true);                           // Display form to user
    }
    
    /**
     * Add the text in the textbox into the LinkedList data structure
     */
    private void addToList() {
        String text = enterTextField.getText();         // Get text from textbox
        list.add(text);                                 // Add to the LinkedList
        enterTextField.setText("");                 // Clear text out of textbox
        enterTextField.requestFocus();              // Put focus back on textbox
    }
        
    /**
     * Display the entire contents of the dynamic LinkedList ADT in the listbox
     * control on the form
     */
    public void showList() {
        for (int i = 0; i < list.size(); i++) {           // Traverse LinkedList
            String text = list.get(i);               // Get text from LinkedList
            itemsList.add(text);                       // Add to listbox control
        }
    }

    /**
     * Action responding to the user pressing a key
     * 
     * @param event the specific key event pressed
     */
    private void keypress(KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.VK_ENTER) {         // Only Enter key
            addToList();                                  // Call to add to list
        }
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="NetBeans Generated Code">
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();
        enterTextField = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        itemsList = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Example");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        textLabel.setText("Example:");

        enterTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterTextFieldKeyPressed(evt);
            }
        });

        enterButton.setText("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        enterButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterButtonKeyPressed(evt);
            }
        });

        showButton.setText("SHOW");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        showButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(enterButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(showButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(enterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemsList, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        addToList();
    }//GEN-LAST:event_enterButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        showList();
    }//GEN-LAST:event_showButtonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        keypress(evt);
    }//GEN-LAST:event_formKeyPressed

    private void enterButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterButtonKeyPressed
        keypress(evt);
    }//GEN-LAST:event_enterButtonKeyPressed

    private void enterTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterTextFieldKeyPressed
        keypress(evt);
    }//GEN-LAST:event_enterTextFieldKeyPressed

    private void showButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showButtonKeyPressed
        keypress(evt);
    }//GEN-LAST:event_showButtonKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField enterTextField;
    private java.awt.List itemsList;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    
}
