/** Required package class namespace */
package testing.extras.graphics;

import java.awt.Color;


/**
 * SimpleDesigerUserInterface.java - this example uses the NetBeans designer  
 * to help with building a layout quicker and without much coding. 
 * 
 * THE DESIGN
 * ==========
 * 
 * The designer is used and a number of controls are added from the palette 
 * and the properties of each are set using the properties window. If you
 * are building a project in this way, I recommend that you should take the 
 * time to right click every label and go to "Change Variable Name" and name 
 * each control so that it is easier to identify them in code later.
 * 
 * THE CODE
 * ========
 * The code can be found below. You can switch between code and designer mode by
 * clicking the "Source" and "Design" buttons just under the top of this tab.
 * Also, when you add a Frame/Form, the NetBeans designer always adds a "main"
 * method that you can keep or delete (I have deleted it from this form).
 
 *
 * @author Mr. Wachs
 * @since December 2024
 */
public class SimpleDesigerUserInterface extends javax.swing.JFrame 
{

    /** 
     * Constructor method, creates new frame/form UserInterface 
     */
    public SimpleDesigerUserInterface() {
        initComponents();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        designerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        designerButton.setText("EXIT");
        designerButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                designerButtonMouseMoved(evt);
            }
        });
        designerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(designerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(designerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void designerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designerButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Another click");
    }//GEN-LAST:event_designerButtonActionPerformed

    private void designerButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designerButtonMouseMoved
        // TODO add your handling code here:
        designerButton.setBackground(Color.red);
    }//GEN-LAST:event_designerButtonMouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton designerButton;
    // End of variables declaration//GEN-END:variables

}
