
/** Required package class namespace */
package testing.project;


/**
 * AllUsersUI.java - description
 *
 * @author Mr. Wachs
 * @since May 23, 2025, 10:46:58 a.m.
 */
public class AllUsersUI extends javax.swing.JFrame 
{

    /** 
     * Constructor method, creates new frame/form AllUsersUI 
     */
    public AllUsersUI() {
        initComponents();
        this.setResizable(false);
        this.setSize(445, 230);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(list1);
        list1.setBounds(10, 40, 210, 140);

        jLabel2.setText("Names:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 80, 20);

        jButton1.setText("Save User List");
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 140, 190, 40);

        jButton2.setText("Delete Selected User");
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 90, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

}
