
/** Required package class namespace */
package testing.project;


/**
 * GUI.java - description
 *
 * @author Mr. Wachs
 * @since May 22, 2025, 10:23:52 a.m.
 */
public class LoginUI extends javax.swing.JFrame 
{

    /** 
     * Constructor method, creates new frame/form GUI 
     */
    public LoginUI() {
        initComponents();
        this.setResizable(false);
        this.setSize(215, 230);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        seeAllUsersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        usernameLabel.setText("Username:");
        getContentPane().add(usernameLabel);
        usernameLabel.setBounds(10, 20, 90, 20);

        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(10, 50, 90, 20);
        getContentPane().add(usernameTextField);
        usernameTextField.setBounds(100, 20, 90, 22);
        getContentPane().add(passwordPasswordField);
        passwordPasswordField.setBounds(100, 50, 90, 22);

        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(10, 90, 180, 23);

        newUserButton.setText("NEW USER");
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newUserButton);
        newUserButton.setBounds(10, 120, 180, 23);

        seeAllUsersButton.setText("SEE ALL USERS");
        seeAllUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAllUsersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seeAllUsersButton);
        seeAllUsersButton.setBounds(10, 150, 180, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        AllUsersUI allUsersUI = new AllUsersUI();
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserButtonActionPerformed

    private void seeAllUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAllUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seeAllUsersButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JButton seeAllUsersButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
