
/** Required package class namespace */
package testing.project;


/**
 * UIAllUsers.java - a user interface (UI) NetBeans designer class to show all 
 * users in the database
 *
 * @author Mr. Wachs
 * @since May 24, 2025
 */
public class UIAllUsers extends javax.swing.JFrame 
{

    /** 
     * Constructor method, creates new frame/form AllUsersUI 
     */
    public UIAllUsers() {
        initComponents();                     // NetBeans designer method called
        Database.addUsers(usersList);             // Load all users into listbox
        UIManager.start(this, 445, 230);            // Set UI look and show user
    }

    // <editor-fold defaultstate="collapsed" desc="NetBeans Editor Generated Code"> 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        namesLabel = new javax.swing.JLabel();
        usersList = new java.awt.List();
        deleteSelectedUserButton = new javax.swing.JButton();
        returnToLoginButton = new javax.swing.JButton();
        saveUserListButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database");
        getContentPane().setLayout(null);

        namesLabel.setText("Names:");
        getContentPane().add(namesLabel);
        namesLabel.setBounds(10, 10, 80, 20);
        getContentPane().add(usersList);
        usersList.setBounds(10, 40, 210, 140);

        deleteSelectedUserButton.setText("Delete Selected User");
        deleteSelectedUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteSelectedUserButton);
        deleteSelectedUserButton.setBounds(230, 40, 190, 40);

        returnToLoginButton.setText("Return To Login");
        returnToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnToLoginButton);
        returnToLoginButton.setBounds(230, 90, 190, 40);

        saveUserListButton.setText("Save User List");
        saveUserListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUserListButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveUserListButton);
        saveUserListButton.setBounds(230, 140, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // </editor-fold> 
    
    private void returnToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToLoginButtonActionPerformed
        UIManager.loadLogin(this);                           // Move to Login UI
    }//GEN-LAST:event_returnToLoginButtonActionPerformed

    private void deleteSelectedUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedUserButtonActionPerformed
        int index = usersList.getSelectedIndex();      // Get user selected item
        if (index == -1) {              // Error check the user made a selection
            Message.showNotSelected(this);                  // Message user this
        }
        else {                                    // User made a valid selection
            if (Message.confirmDelete(this,index)) {         // Confirm deletion
                Database.remove(index);             // Remove user from database
                Database.addUsers(usersList);     // Load all users into listbox
            }
        }        
    }//GEN-LAST:event_deleteSelectedUserButtonActionPerformed

    private void saveUserListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUserListButtonActionPerformed
        if (Message.confirmSave(this)) {              // Confirm saving database 
            Database.save();                  // Save database to permanent file
            UIManager.loadLogin(this);                       // Move to Login UI
        }        
    }//GEN-LAST:event_saveUserListButtonActionPerformed

    // <editor-fold defaultstate="collapsed" desc="NetBeans Editor UI Controls">
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteSelectedUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namesLabel;
    private javax.swing.JButton returnToLoginButton;
    private javax.swing.JButton saveUserListButton;
    private java.awt.List usersList;
    // End of variables declaration//GEN-END:variables

    // </editor-fold> 
    
}
