
/** Required package class namespace */
package testing.project;


/**
 * UILogin.java - a user interface (UI) for the application user to login to a
 * potential program. This class uses the NetBeans visual editor to design the
 * UI, add controls (objects) from the pallette, and change properties using 
 * the properties window of the NetBeans designer. However, much of the logic 
 * for this program shifts to other classes and other UI classes such as:
 *  - UIManager: a class to shift some of the UI logic for the various UIs
 *  - Database: a class to manage a LinkedList representing a database of users
 *  - Message: a class to send simple dialog messages to the user
 *  - User: a class representing a program user with username and password
 *  - UIAllUsers: a UI designer class to show all users in the database
 *  - UIProject: a UI designer class that has the potential to be a project
 *
 * @author Mr. Wachs
 * @since May 24, 2025
 */
public class UILogin extends javax.swing.JFrame 
{

    /** 
     * Constructor method, creates new frame/form GUI 
     */
    public UILogin() {
        initComponents();                     // NetBeans designer method called
        Database.open();              // Open saved database from permanent file
        UIManager.start(this, 215, 230);            // Set UI look and show user
    }

    // <editor-fold defaultstate="collapsed" desc="NetBeans Editor Generated Code">
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        seeAllUsersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database");
        getContentPane().setLayout(null);

        usernameLabel.setText("Username:");
        getContentPane().add(usernameLabel);
        usernameLabel.setBounds(10, 20, 90, 20);

        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(10, 50, 90, 20);
        getContentPane().add(usernameField);
        usernameField.setBounds(100, 20, 90, 20);
        getContentPane().add(passwordField);
        passwordField.setBounds(100, 50, 90, 20);

        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(10, 90, 180, 23);

        newUserButton.setText("NEW USER");
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newUserButton);
        newUserButton.setBounds(10, 120, 180, 23);

        seeAllUsersButton.setText("SEE ALL USERS");
        seeAllUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAllUsersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seeAllUsersButton);
        seeAllUsersButton.setBounds(10, 150, 180, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // </editor-fold> 
    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Verify the textbox data for the username and password fields
        if (UIManager.validate(this, usernameField, passwordField)) {
            // Get data for creating (instantiating) a User object
            User user = UIManager.getUser(usernameField, passwordField);    
            if (Database.isValid(user)) {                 // User is in database
                Message.showValid(user,this);               // Message user this
                UIManager.loadProject(this);               // Move to Project UI
            }
            else {                                    // User is not in database
                Message.showInvalid(this, "Invalid username and/or password!");
                UIManager.clear(usernameField,passwordField);    // Clear inputs
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        // Verify the textbox data for the username and password fields
        if (UIManager.validate(this, usernameField, passwordField)) {
            // Get data for creating (instantiating) a User object
            User user = UIManager.getUser(usernameField, passwordField);       
            if (Database.isValid(user)) {            // User already in database
                Message.showAlreadyUser(user,this);         // Message user this
                UIManager.clear(usernameField,passwordField);    // Clear inputs
            }
            else {                               // New user not in the database
                if (Message.confirmNew(user,this)) {      // Confirm want to add
                    Message.showAdded(user,this);           // Message user this
                    Database.add(user);                  // Add user to database
                    UIManager.loadAllUsers(this);        // Move to All Users UI
                }               
            }
        }
    }//GEN-LAST:event_newUserButtonActionPerformed

    private void seeAllUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAllUsersButtonActionPerformed
        UIManager.loadAllUsers(this);                    // Move to All Users UI
    }//GEN-LAST:event_seeAllUsersButtonActionPerformed

    // <editor-fold defaultstate="collapsed" desc="NetBeans Editor UI Controls">
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton seeAllUsersButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    // </editor-fold> 
    
}
